import streamlit as st

st.title('APLICACIÓN WEB')
st.header('NUTRIGUIA')
st.image('https://raw.githubusercontent.com/udaml-1/nutriguia/main/LOGO.jpg')
st.subheader('App creada por New Version Team')
st.subheader('Integrantes.' )
st.write('- Mitzy Ramirez Flores')
st.write('- Estefany Silva Piñón')
st.write('- Daniela Salinas García')
st.write('- Jesus R. Mata Morales')

st.write('**NUTRIGUIA** busca mejorar la calidad de vida de las personas desde sus hogares implementando planes alimenticios y deportivos o que ellos mismos formen sus planes adecuandolos a sus necesidades y posibilidades de su cuerpo, ademas de datos interesantes sobre los alimentos.')
st.image('https://controlkilos.org/wp-content/uploads/2019/06/comida-y-ejercicos-520x434.jpg')

st.write('A partir de tu información podremos ayudarte a realizar una rutina y un plan de alimentacion adecuado.')
st.text("Contesta lo siguiente:")

edad = st.text_input('¿Qué edad tienes?')
#st.write(edad)
sexo= st.radio('¿Cuál es tu sexo?', ['Femenino','Masculino'])
#st.write(sexo)
estatura = st.slider('¿Cuál es tu estatura? En metros.', min_value=1.0, max_value=2.0)
#st.write(estatura)
peso = st.slider('¿Cuál es tu peso? En Kilogramos.', min_value=30.0, max_value=150.0)
#st.write(peso)
tipo_de_ejercicio = st.radio('¿Qué tipo de ejercicio deseas realizar?',['Cardio','Pesas','Deporte'])
#st.write(tipo_de_ejercicio)
plan_alimenticio = st.radio('¿Realizas algún tipo de plan alimenticio?',['Sí, cuento con uno.','No realizo ninguno.'])
#st.write(plan_alimenticio)
propuesta = st.radio('Si tu respuesta fue no, ¿Te gustaría iniciar uno?',['Si, sería una buena idea.','No, no estoy interesad@'])
#st.write(propuesta)
pregunta1 = st.selectbox('¿Cuántas veces comes al día?', [1,2,3,4,5])
#st.write(pregunta1)
pregunta2 = st.multiselect('Selecciona si tienes alguno de estos habitos recurrentemente', ["TOMAR ALCOHOL","FUMAR"])
#st.write(pregunta2)
pregunta3 = st.radio('¿Tienes alguna enfermedad crónica?', ["SI","NO"])
#st.write(pregunta3)
pregunta4 = st.text_input('¿Cuál?')
#st.write(pregunta4)

import streamlit as st
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
import pandas as pd

st.header('Nutrichat')
st.write('En este espacio puedes introducir preguntas sencillas para que Nutribot nuestro robot nuticional te ayude respondiendo, algunos ejemplos pueden ser: ¿Qué puedes hacer?, ¿Me puedes dar un consejo de salud?, ¿De qué me sirve conocer el IMC?, entre otas cosas.')

df = pd.read_csv('https://raw.githubusercontent.com/udaml-1/nutriguia/main/CHBSC.csv')


input_text = st.text_input('Yo: ', '')

talk = df['NutriBot'].tolist()

Nutri = ChatBot('Nutrichat')

trainer = ListTrainer(Nutri)

trainer.train(talk)

respuesta_chat = Nutri.get_response(input_text)

st.write('🤖',respuesta_chat)

st.subheader('Calculadora para IMC(Indice de Masa Corporal).')
st.image('https://image.freepik.com/vector-gratis/mujeres-diminutas-cerca-escalas-grafico-obeso-aislaron-ejemplo-plano-vector-personajes-femeninos-dibujos-animados-dieta-usando-control-peso-imc-indice-masa-corporal-concepto-ejercicio-fisico-medico_74855-10177.jpg')
st.write('El IMC es un valor orientativo y de medida que permite realizar una valoración del peso corporal.')
st.write('¿Como se calcula?')
st.write('Se calcula dividiendo los kilogramos de peso por el cuadrado de la estatura en metros.')
st.latex(r'''Indice de Masa Corporal = \frac{Peso}{Estarura^2}''')

#st.write(valorpeso)
valorpeso = st.write ('Peso reportado en Kilogramos')
Masa = peso 
st.write(peso)

#st.write (valorestatura)
valorestatura = st.write ('Estatura reportada en Metros')
Altura = estatura 
st.write(estatura)

imc = peso/estatura**2
cal = st.button('Presiona para calcular')
if cal==True:
    st.write('El IMC es' , imc)
    if imc < 18.5:
        st.subheader('Se encuentra en PESO BAJO')        
        st.subheader('POSIBLES CAUSAS')
        st.write('Van desde la genética hasta las afecciones médicas, incluidas la depresión y la ansiedad, o los desórdenes alimentarios como la anorexia nerviosa.')
        st.subheader('RECOMENDACIONES')
        st.write('Lo que sugiere que usted tiene un peso bajo. Debe alcanzar ademas de mantener un peso adecuado puede ayudarlo a combatir las enfermedades y disfrutar de una buena salud general.')
        st.write('Agregue calorías saludables.')
        st.write('Opte por alimentos ricos en nutrientes.')
        st.write('No restrinja la merienda.')
        st.write('Incorpore comidas pequeñas.')
        st.write('Aumente la masa muscular.')
        st.image('https://cdn2.salud180.com/sites/default/files/styles/medium/public/field/image/2017/11/mujer_delgada_editada.jpg')
        
    if imc >= 18.5 and imc<24.9:
        st.subheader('Se encuentra en PESO NORMAL')
        st.write('Se considera un peso saludable  aquel que nos permite mantenernos en un buen estado de salud y calidad de vida.  También se entiende como  los valores de peso, dentro de los cuales, no existe riesgo para la salud de la persona.')
        st.subheader('RECOMENDACIONES PARA ALCANZAR UN PESO NORMAL:')
        st.write('1. Ejercicio físico:La actividad física regular quema calorías y genera tejido muscular. Estas dos cosas te ayudan a verte y sentirte bien y a no recuperar el peso perdido.')
        st.write('2. Reduce el tiempo ante la pantalla: Establece límites razonables para la cantidad de tiempo que pasas frente al televisor, jugando videojuegos y usando computadoras, teléfonos y tabletas sin razones relacionadas con el trabajo escolar.')
        st.write('3. Ten cuidado con las porciones distorsionadas: Las grandes porciones agregan calorías que te hacen subir de peso. ')
        st.write('4. Come 5 porciones de frutas y verduras por día: Las frutas y verduras son mucho más que simplemente vitaminas y minerales. También están llenas de fibra, lo cual significa que te llenarán. Y cuando te llenas con frutas y verduras, tienes menos probabilidades de comer demás.')
        st.write('5. No te saltees el desayuno: El desayuno pone en marcha tu metabolismo, para que queme calorías desde el principio, y te da energía para hacer más cosas durante el día. Las personas que se saltean el desayuno suelen estar tan hambrientas que más tarde comen más.  ')
        st.image('http://vidaybienestar.mx/wp-content/uploads/2013/03/Captura-de-pantalla-2016-11-11-a-las-12.10.14.png')

    if imc >= 25 and imc<29.9:
        st.subheader('Se encuentra en SOBREPESO')
        st.write('Sobrepeso, significa pesar demasiado.')
        st.write('Algunas personas en este grupo, como los atletas, pueden tener mucho peso muscular y por lo tanto no tanta grasa. Estas personas no tendrán un aumento del riesgo de problemas de salud debido a su peso.')
        st.subheader('CAUSAS')
        st.write('Falta de actividad física.')
        st.write('Alimentación inadecuada: Exceso en el consumo de alimentos procesados y con alta cantidad de grasa, así como, alta ingesta de refrescos y alcohol.')
        st.write('Genética.')
        st.write('Estilo de vida: El sedentarismo no ayuda a controlar el peso.')
        st.write('Algunas enfermedades y medicamentos administrados de forma periódica.')
        st.subheader('RECOMENDACIONES')
        st.write('1. Cambiar el estilo de vida.')
        st.write('2. Un estilo de vida activo y mucho ejercicio, junto con una alimentación saludable, es la forma más segura de bajar de peso.')
        st.write('3. Su objetivo principal debe ser aprender nuevas formas de comer saludable e incorporarlas a su rutina diaria.')
        st.write('4. Convierta el cambio de comportamiento en parte de su vida a largo plazo. Sepa que se necesita tiempo para hacer y mantener un cambio en su estilo de vida.')
        st.image('http://www.farmaceuticosdesevilla.es/files/articles/image/1547573369-obese-3011213_640.jpg')

    if imc >= 30 and imc<34.9:
        st.subheader('Esta en OBESIDAD DE TIPO I')
        st.write('Obesidad significa tener mucha grasa corporal.')
        st.subheader('CAUSAS')
        st.write('Falta de actividad física.')
        st.write('Alimentación inadecuada: Exceso en el consumo de alimentos procesados y con alta cantidad de grasa, así como, alta ingesta de refrescos y alcohol.')
        st.write('Genética.')
        st.write('Estilo de vida: El sedentarismo no ayuda a controlar el peso.')
        st.write('Algunas enfermedades y medicamentos administrados de forma periódica.')
        st.subheader('RECOMENDACIONES')
        st.write('1. Limitar el consumo de alimentos que sean ricos en azúcares y grasas. ')
        st.write('2. Comer varias veces al día fruta y verdura, así como legumbres, cereales integrales y frutos secos.')
        st.write('3. Realizar actividad física frecuente: unos 60 minutos por día para los jóvenes y 150 minutos semanales para los adultos. En el caso de que haya un alto grado de obesidad, se recomienda comenzar por caminar 30 minutos al día a paso ligero. ')
        st.write('4. Deja de fumar.')
        st.write('5. Es importante no obsesionarse, pero puede ayudar a controlar el peso pesarse regularmente: una vez por semana es suficiente.')

    if imc >= 35 and imc< 39.9:
        st.subheader('Se encuentra en OBESIDAD SEVERA O DE TIPO II')
        st.subheader('CAUSAS')
        st.write('La ingesta de nutrientes con alto contenido en grasa.')
        st.write('El sedentarismo, conlleva una disminución del gasto energético.')
        st.write('La inestabilidad emocional.')
        st.subheader('RECOMENDACIONES')
        st.write('1. Modificación de la conducta.')
        st.write('2. Ejercicio físico.')
        st.write('3. Tratamiento farmacológico.')
        st.write('4. Cirugía bariátrica.')
        st.image('https://lacalletv.com/wp-content/uploads/2020/08/La-obesidad-severa-esta-relacionada-con-un-mayor-riesgo-de-muerte-por-coronavirus-2-1-1280x720.jpg')

    if imc>= 40:
        st.subheader('Se encuentra en OBESIDAD MORBIDA O DE TIPO III')
        st.write('Se caracteriza por el aumento progresivo de la masa corporal hasta alcanzar un punto en el que este aumento supone un riesgo para la salud del paciente')
        st.subheader('CAUSAS')
        st.write('La ingesta de productos con alto valor calórico, asociado a un estilo de vida sedentario y poco sano suele ser el principal culpable del cambio en el peso de la persona.')
        st.write('Factores genéticos.')
        st.write('Factores ambientales.')
        st.write('Factores psicológicos.')
        st.subheader('RECOMENDACIONES')
        st.write('1. Realizar ejercicio de forma regular.')
        st.write('2. Llevar una alimentación sana y equilibrada: ingerir alimentos ricos en nutrientes y con pocas calorías es vital.')
        st.write('3. Identificar y evitar situaciones fuera de control.')
        st.write('4. Controlar el peso: pesarse al menos una vez a la semana ayuda a mantener el peso y ser constante.')
        st.subheader('TRATAMIENTO')
        st.write('Existen dietas específicas combinadas con ejercicio que pueden ayudar a disminuir una parte importante del exceso de peso. ')
        st.write('En los casos en los que ni dieta ni ejercicio se muestran como tratamientos efectivos, se plantea la opción de llevar a cabo una intervención quirúrgica.')
        st.image('https://static4.abc.es/media/salud/2020/09/29/4478256-klIH--620x349@abc.jpg')



st.subheader('Calculadora para ICC(Indice Cintura-Cadera).')
st.image('https://avalon.fabiosacdn.com/image/4937aa51-6d96-432c-9a71-6aac807776b9.jpg')
st.write('El índice cintura-cadera (ICC) es una medida antropométrica específica para medir los niveles de grasa intraabdominal.')
st.write('¿Cómo se calcula?')
st.write('Se obtiene midiendo el perímetro de la cintura a la altura de la última costilla flotante, y el perímetro máximo de la cadera a nivel de los glúteos.')
st.latex(r'''Indice Cintura-Cadera = \frac{Cintura}{Cadera}''')

cintura = st.number_input('Escribe la longitud de la circunferencia de cintura en Cm',50)
st.write(cintura)

cadera = st.number_input('Escriba la longitud de la circunferencia de la cadera en Cm',50)
st.write(cadera)

#st.write(Sexo)
Sexo = st.write ('Sexo reportado')
Sexo = sexo
st.write(Sexo)

icc = cintura/cadera
Boton = st.checkbox('Presiona para calcular ICC')

if sexo == 'Femenino' and True== Boton:
   st.write('El ICC es' , icc)
   if icc <.85:
       st.write ('RIESGO BAJO')
       st.write ('CONSECUENCIAS')
       st.write ('◆ Indica bajo riesgo de desarrollar problemas cardiovasculares')
       st.write ('RECOMENDACIÓN')
       st.write ('◉ Es importante mantener el peso controlado con una alimentación saludable y actividad física regular.')
       st.write ('◉ Realiza entre 4 o 5 ingestas al día para evitar llegar a las comidas principales con un hambre excesiva. Para estas ingestas elige alimentos saludables y que te sacien.')
       st.write ('◉ Integra en tu dieta diaria alimentos ricos en fibra como verduras y frutas, preferentemente consúmelas crudas y con cáscara. ')
       st.write ('◉ Haz ejercicio físico regular mediante algún tipo de práctica deportiva. Pasear o practicar algún deporte.')
       st.image('https://static.tuasaude.com/media/article/fc/xp/relacao-cintura-quadril_30884_l.jpg')
   
   if icc >= .86 and icc<1.5:
       st.write ('RIESGO ALTO')
       st.write('COSECUENCIAS')
       st.write('◆ Indica que tienes un alto riesgo de desarrollar enfermedades cardiovasculares como por ejemplo: diabetes tipo 2, hipertensión o angina de pecho.')
       st.write('RECOMENDACIÓN') 
       st.write('◉ Es importante que si alguien de tu familia sufre de hipertensión o ya tuvo un ACV, te realices exámenes de sangre y consultes a un cardiólogo para una evaluación completa de salud cardiovascular.')
       st.write('◉ Promover una dieta equilibrada, con mayor consumo de frutas y verduras, legumbres, granos enteros, y fibra.')
       st.write('◉ Aumentar la disponibilidad, la accesibilidad y el consumo de agua simple potable.')
       st.write('◉ Realizar actividad física regular en los entornos escolar, laboral, comunitario y de ocio.')
       st.image('https://concepto.de/wp-content/uploads/2018/09/obesidad-e1537202474480.jpg')

if sexo == 'Masculino'and True== Boton:
   st.write('El ICC es' , icc)
   if icc <.95:
       st.write ('RIESGO BAJO')
       st.write ('CONSECUENCIAS')
       st.write ('◆ Indica bajo riesgo de desarrollar problemas cardiovasculares')
       st.write ('RECOMENDACIÓN')
       st.write ('◉ Es importante mantener el peso controlado con una alimentación saludable y actividad física regular.')
       st.write ('◉ Realiza entre 4 o 5 ingestas al día para evitar llegar a las comidas principales con un hambre excesiva. Para estas ingestas elige alimentos saludables y que te sacien.')
       st.write ('◉ Integra en tu dieta diaria alimentos ricos en fibra como verduras y frutas, preferentemente consúmelas crudas y con cáscara. ')
       st.write ('◉ Haz ejercicio físico regular mediante algún tipo de práctica deportiva. Pasear o practicar algún deporte.')
       st.image('https://dracampanari.com/wp-content/uploads/2014/05/liposuccion-hombres.jpg')
   
   if icc >= .96 and icc<2:
       st.write ('RIESGO ALTO') 
       st.write('COSECUENCIAS')
       st.write('◆ Indica que tienes un alto riesgo de desarrollar enfermedades cardiovasculares como por ejemplo: diabetes tipo 2, hipertensión o angina de pecho.')
       st.write('RECOMENDACIÓN') 
       st.write('◉ Es importante que si alguien de tu familia sufre de hipertensión o ya tuvo un ACV, te realices exámenes de sangre y consultes a un cardiólogo para una evaluación completa de salud cardiovascular.')
       st.write('◉ Promover una dieta equilibrada, con mayor consumo de frutas y verduras, legumbres, granos enteros, y fibra.')
       st.write('◉ Aumentar la disponibilidad, la accesibilidad y el consumo de agua simple potable.')
       st.write('◉ Realizar actividad física regular en los entornos escolar, laboral, comunitario y de ocio.')
       st.image('https://www.obescorporacion.com/wp-content/uploads/2017/11/obesidadhombres_obescorporacion_alicante.jpg')

st.subheader('¿Deseas una rutina de ejercicio?')

st.write('**NUTRIGUIA**, te proporciona rutinas especiales para que puedas hacer ejercicio en casa.')
st.image('https://d2lcsjo4hzzyvz.cloudfront.net/blog/wp-content/uploads/2019/07/29153824/Mujer-app-casa-760x501.jpg')
st.write('En la seccion de la barra lateral encontraras rutinas tanto para hombre como para mujer, seguido del dia de la semana.')


st.sidebar.header('◆ RUTINAS.')

st.sidebar.subheader('MUJER.🏋️‍♀️')
mujer = st.sidebar.selectbox('Selecciona el dia de la semana correspondiente.',['','LUNES','MARTES','MIERCOLES','JUEVES','VIERNES'])

if mujer == 'LUNES':
  st.sidebar.subheader('CUADRICEPS Y PANTORRILLA')
  st.sidebar.write('Sentadillas 4 series de 15')
  st.sidebar.image('https://i.pinimg.com/originals/0f/ce/80/0fce809ca12203945e57eafabd813db3.gif')
  st.sidebar.write('Sentadilla estatica 4 series de 12')
  st.sidebar.image('https://i0.wp.com/pilicuadrado.com/wp-content/uploads/2016/04/katie-chung-huas-dorm-room-workout-6.jpg?w=560&ssl=1')
  st.sidebar.write('desplantes 4 series de 20 en cada pierna')
  st.sidebar.image('https://www.recreoviral.com/wp-content/uploads/2017/01/Desplantes-en-reversa.gif')
  st.sidebar.write('Peso muerto 4 series de 12')
  st.sidebar.image('https://www.womenshealthlatam.com/wp-content/uploads/2019/10/Ej-5-Peso-muerto-rumano.gif')
  st.sidebar.write('Abduccion isometrica 2 series de 25')
  st.sidebar.image('https://aws.glamour.es/prod/designs/v1/assets/620x341/592270.gif')
  st.sidebar.write('sentadilla con salto, 2 series de 30')
  st.sidebar.image('https://i.pinimg.com/originals/04/19/ef/0419ef42dcec9ce1334feaa28045aba7.gif')


if mujer == 'MARTES':
  st.sidebar.subheader('ESPALDA, TRICEPS, HOMBRO Y ABDOMEN')
  st.sidebar.write('Comando 4 series de 12')
  st.sidebar.image('http://guiasaludable.net/wp-content/uploads/2015/05/planchacomandos.gif')
  st.sidebar.write('Traccion 4 series de 10')
  st.sidebar.image('https://media.self.com/photos/59382bbf8d931f75f99712a0/master/w_1600%2Cc_limit/dumbell14.gif')
  st.sidebar.write('Remo 2 series de 15')
  st.sidebar.image('https://www.snapfitness.com/assets/BlogImages/9e13a8978d/141bb65007b275a30eaca85203a505e8.gif')
  st.sidebar.write('Frances 4 series de 12')
  st.sidebar.image('https://i1.wp.com/www.gimnasiogym.net/wp-content/uploads/2021/03/press-frances-3.gif?resize=360%2C360&ssl=1')
  st.sidebar.write('Fondos 4 series de 12')
  st.sidebar.image('http://www.cutypaste.com/wp-content/uploads/2016/10/TricepDipBox.gif')
  st.sidebar.write('Copa 4 series de 15')
  st.sidebar.image('https://static.wixstatic.com/media/f593a9_53d79d8bfc9b425a85aa9a39338835b1~mv2.gif')
  st.sidebar.write('Abdominales cortas 4 series de 20')
  st.sidebar.image('https://eslamoda.com/wp-content/uploads/sites/2/2014/04/abdominales9.gif')
  st.sidebar.write('Plancha 4 series de 20 seg')
  st.sidebar.image('https://2.bp.blogspot.com/-F_o6fEBEuyc/WodJPrEk-VI/AAAAAAAAbB0/DTa3Nvy7Beg4R7D-UbGVb1NoiZ4NqE5OwCLcBGAs/s1600/step%2Bby%2Bstep%2Bexercises%2Bplank.gif')
  st.sidebar.write('Bicicletas 4 series de 20')
  st.sidebar.image('http://www.elattelier.com/wp-content/uploads/2015/11/Bicycle-Crunch-GIF-3_zpsfaiudx4f.gif')
  st.sidebar.write('Elevación de pierna 4 series de 20')
  st.sidebar.image('https://i.pinimg.com/originals/52/da/e4/52dae439cc246e0b6c7263d7b3536234.gif')



if mujer == 'MIERCOLES':
  st.sidebar.subheader('FEMORAL Y GLUTEO')
  st.sidebar.write('Sentadilla de zumo 4 series de 15 ')
  st.sidebar.image('https://static.wixstatic.com/media/f593a9_2e0763fc9f534e95acbc95fb46831338~mv2.gif')
  st.sidebar.write('Zancadas 4 series de 20')
  st.sidebar.image('https://static.wixstatic.com/media/f593a9_9b3cc983321b4eb487c68295c5a7e49f~mv2.gif')
  st.sidebar.write('Puente 4 series de 15 ')
  st.sidebar.image('https://css.adelgazarencasa.co/wp-content/uploads/2019/07/Puente.gif')
  st.sidebar.write('Abductor 2 series de 25')
  st.sidebar.image('https://aws.glamour.es/prod/designs/v1/assets/620x341/592270.gif')
  st.sidebar.write('Leg Curl 4 series de 12')
  st.sidebar.image('https://thumbs.gfycat.com/FavoriteFaintAlpineroadguidetigerbeetle-small.gif')
  st.sidebar.write('Patada de mula 2 series de 30 cada pierna')
  st.sidebar.image('https://2.bp.blogspot.com/-B1ntGW0NYnI/Wor87JudjQI/AAAAAAAAbGY/bdreziuiuXAtX9FDHokLrd2ba7WAVFDJQCLcBGAs/s1600/step%2Bby%2Bstep%2Bexercises%2Bpatada%2Bde%2Bburro.gif')


if mujer == 'JUEVES':
  st.sidebar.subheader('PECHO, BICEPS Y ABDOMEN')
  st.sidebar.write('Curl concentrado 2 series de 15')
  st.sidebar.image('https://static.wixstatic.com/media/f593a9_59c95a40eee448abbe6364bbbd7ed64a~mv2.gif')
  st.sidebar.write('Curl con mancuerna 2 series de 15')
  st.sidebar.image('https://i.pinimg.com/originals/a2/86/0f/a2860fb708fcf5519be6354a3e6db15c.gif')
  st.sidebar.write('Dominadas cerradas 2 fallos')
  st.sidebar.image('https://www.foodspring.de/magazine/wp-content/uploads/2020/11/Pull-Up-With-Support.gif')
  st.sidebar.write('Press de banco horizontal 4 series de 12')
  st.sidebar.image('https://creatucuerpo.com/wp-content/uploads/2020/04/dumbbell-bench-press.gif')
  st.sidebar.write('Press vertical 4 series de 12')
  st.sidebar.image('https://i.pinimg.com/originals/e9/cc/e2/e9cce2caed67125495d0226ffd867141.gif')
  st.sidebar.write('Lagartija cerrada 2 fallos')
  st.sidebar.image('https://lh3.googleusercontent.com/proxy/BGOvscqJ-F-ZgTo2TNcsslrI7UBkl4jrRrK0fedCqQkA_l9DJDCAb9tc9oHJ2xSf4rFihZJp_G802kBVycOXQiLVcMb3S91OOMxiCqJ9ut7wuBAKmNFejXyG0YHiIc40FZIV_xFV0GsRPprE')
  st.sidebar.write('Abdominales cortas 4 series de 20')
  st.sidebar.image('https://eslamoda.com/wp-content/uploads/sites/2/2014/04/abdominales9.gif')
  st.sidebar.write('Plancha 4 series de 20 seg')
  st.sidebar.image('https://2.bp.blogspot.com/-F_o6fEBEuyc/WodJPrEk-VI/AAAAAAAAbB0/DTa3Nvy7Beg4R7D-UbGVb1NoiZ4NqE5OwCLcBGAs/s1600/step%2Bby%2Bstep%2Bexercises%2Bplank.gif')
  st.sidebar.write('Bicicletas 4 series de 20')
  st.sidebar.image('http://www.elattelier.com/wp-content/uploads/2015/11/Bicycle-Crunch-GIF-3_zpsfaiudx4f.gif')
  st.sidebar.write('Elevacion de piernas 4 series de 20')
  st.sidebar.image('https://i.pinimg.com/originals/52/da/e4/52dae439cc246e0b6c7263d7b3536234.gif')



if mujer == 'VIERNES':
  st.sidebar.subheader('CUADRICEPS Y PANTORRILLA')
  st.sidebar.write('Sentadillas 4 series de 15')
  st.sidebar.image('https://i.pinimg.com/originals/0f/ce/80/0fce809ca12203945e57eafabd813db3.gif')
  st.sidebar.write('Sentadilla estatica 4 series de 12')
  st.sidebar.image('https://i0.wp.com/pilicuadrado.com/wp-content/uploads/2016/04/katie-chung-huas-dorm-room-workout-6.jpg?w=560&ssl=1')
  st.sidebar.write('desplantes 4 series de 20 en cada pierna')
  st.sidebar.image('https://www.recreoviral.com/wp-content/uploads/2017/01/Desplantes-en-reversa.gif')
  st.sidebar.write('Peso muerto 4 series de 12')
  st.sidebar.image('https://www.womenshealthlatam.com/wp-content/uploads/2019/10/Ej-5-Peso-muerto-rumano.gif')
  st.sidebar.write('Abduccion isometrica 2 series de 25')
  st.sidebar.image('https://aws.glamour.es/prod/designs/v1/assets/620x341/592270.gif')
  st.sidebar.write('sentadilla con salto, 2 series de 30')
  st.sidebar.image('https://i.pinimg.com/originals/04/19/ef/0419ef42dcec9ce1334feaa28045aba7.gif')


st.sidebar.subheader('HOMBRE.🏋️')

hombre= st.sidebar.selectbox('Selecciona el dia de la semana.',['','LUNES','MARTES','MIERCOLES','JUEVES','VIERNES'])
if hombre == 'LUNES':
   st.sidebar.subheader('ESPALDA, TRICEPS Y ABDOMEN')
   st.sidebar.write('Comando 4 series de 12')
   st.sidebar.image('https://i.pinimg.com/originals/ee/30/fc/ee30fc219a5cb0cb6d3cbf40cf7272f9.gif')
   st.sidebar.write('Traccion 4 series de 10')
   st.sidebar.image('https://i.pinimg.com/originals/63/bd/12/63bd12e1f39783894f770ad73ae405d5.gif')
   st.sidebar.write('Remo 2 series de 15')
   st.sidebar.image('https://i.pinimg.com/originals/01/03/7f/01037f1ec873a7d00afad45f33f9d865.gif')
   st.sidebar.write('Frances 4 series de 12')
   st.sidebar.image('https://www.entrenador.fit/wp-content/uploads/Extension-de-triceps-tumbado-con-mancuerna.gif')
   st.sidebar.write('Copa 4 series de 15')
   st.sidebar.image('https://i.pinimg.com/originals/8b/bc/17/8bbc17afff347e32e7216dd072962081.gif')
   st.sidebar.write('Lagartijas 4 series de 15')
   st.sidebar.image('https://2.bp.blogspot.com/-89XQn-i9jkM/WoslsnsiH_I/AAAAAAAAbIA/AJpIZMuPEFQYr1qhm4k1W74SCvpH4QafgCLcBGAs/s1600/step%2Bby%2Bstep%2Bexercises%2Bflexiones.gif')
   st.sidebar.write('Abdominales cortas 4 series de 20')
   st.sidebar.image('https://www.foodspring.de/magazine/wp-content/uploads/2020/11/Crunches-Giannis-1.gif')
   st.sidebar.write('Plancha 4 series de 20 seg')
   st.sidebar.image('https://www.recreoviral.com/wp-content/uploads/2017/01/Plancha.gif')
   st.sidebar.write('Bicicletas 4 series de 20')
   st.sidebar.image('https://2.bp.blogspot.com/-ICToNxoI_Sg/Woh0mJjZ0cI/AAAAAAAAbCw/7_xvGCxu7Mo849NUd3MF3Fy8RJ676BQYwCLcBGAs/s1600/step%2Bby%2Bstep%2Bexercises%2Babdominales%2Bbicicleta.gif')
   st.sidebar.write('Elevacion de piernas 4 series de 20')
   st.sidebar.image('https://www.foodspring.de/magazine/wp-content/uploads/2020/11/Leg-raises-Giannis.gif')

if hombre == 'MARTES':
  st.sidebar.subheader('PIERNA COMPLETA')
  st.sidebar.write('Sentadillas 4 series de 15')
  st.sidebar.image('https://www.eventiglobo.it/wp-content/uploads/2018/12/squat.gif')
  st.sidebar.write('Desplantes 4 series de 20 en cada pierna')
  st.sidebar.image('https://lh3.googleusercontent.com/proxy/0xVG38R_01bQDyNxWCIXh68J-O9_m7ihR8ym7QYD93dqN0Qs4WheFF5hNPlHDfz1dS_XiAWfNijS-ZqqbW2xVTYvdmqm8RHTeXzXckyu_yMqU-B1')
  st.sidebar.write('Peso muerto 4 series de 12')
  st.sidebar.image('https://www.yomeentreno.com/wp-content/uploads/2018/08/55fe8098-7499-4713-983b-3dd0f0f91baf.gif')
  st.sidebar.write('Zancadas 4 series de 20')
  st.sidebar.image('https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/zancadas-1574679139.gif?resize=320:*')
  st.sidebar.write('Puente 4 series de 15 ')
  st.sidebar.image('https://4.bp.blogspot.com/-NJSk3weT0Ds/WoikpGx2ziI/AAAAAAAAbFE/sAix6msp-QMkeN6BryRDX3aBWnb52TPzwCLcBGAs/s1600/step%2Bby%2Bstep%2Bexercises%2Bpuente.gif')
  st.sidebar.write('Abductor 2 series de 25')
  st.sidebar.image('https://www.dir.cat/blog/wp-content/uploads/2018/10/ejercicios-gluteos-puente.gif')
  st.sidebar.write('Leg Curl 4 series de 12')
  st.sidebar.image('https://thumbs.gfycat.com/AltruisticBothAmericantoad-size_restricted.gif')

if hombre == 'MIERCOLES':
  st.sidebar.subheader('PECHO, HOMBRO Y ABDOMEN')
  st.sidebar.write('Dominadas cerradas 2 fallos')
  st.sidebar.image('https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/workouts/2016/03/pullup-1456956490.gif?resize=480:*')
  st.sidebar.write('Press de banco horizontal 4 series de 12')
  st.sidebar.image('https://www.yomeentreno.com/wp-content/uploads/2018/03/07.gif')
  st.sidebar.write('Press vertical 4 series de 12')
  st.sidebar.image('https://risbelmagazine.es/wp-content/uploads/2021/05/Entrenamiento-con-bandas-elasticas.gif')
  st.sidebar.write('Lagartija cerrada 2 fallos')
  st.sidebar.image('https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/flexiones-1552913668.gif?crop=1xw:1xh;center,top&resize=320:*')
  st.sidebar.write('Elevacacion lateral 3 series de 18')
  st.sidebar.image('https://i.imgur.com/Qmpzczz.gif')
  st.sidebar.write('Fondos 4 series de 12')
  st.sidebar.image('https://www.yomeentreno.com/wp-content/uploads/2019/04/Bench-dips.gif')
  st.sidebar.write('Abdominales cortas 4 series de 20')
  st.sidebar.image('https://www.foodspring.de/magazine/wp-content/uploads/2020/11/Crunches-Giannis-1.gif')
  st.sidebar.write('Plancha 4 series de 20 seg')
  st.sidebar.image('https://www.recreoviral.com/wp-content/uploads/2017/01/Plancha.gif')
  st.sidebar.write('Bicicletas 4 series de 20')
  st.sidebar.image('https://2.bp.blogspot.com/-ICToNxoI_Sg/Woh0mJjZ0cI/AAAAAAAAbCw/7_xvGCxu7Mo849NUd3MF3Fy8RJ676BQYwCLcBGAs/s1600/step%2Bby%2Bstep%2Bexercises%2Babdominales%2Bbicicleta.gif')
  st.sidebar.write('Elevacion de piernas 4 series de 20')
  st.sidebar.image('https://www.foodspring.de/magazine/wp-content/uploads/2020/11/Leg-raises-Giannis.gif')

if hombre == 'JUEVES':
  st.sidebar.subheader('PIERNA COMPLETA')
  st.sidebar.write('Sentadillas 4 series de 15')
  st.sidebar.image('https://www.eventiglobo.it/wp-content/uploads/2018/12/squat.gif')
  st.sidebar.write('Desplantes 4 series de 20 en cada pierna')
  st.sidebar.image('https://lh3.googleusercontent.com/proxy/0xVG38R_01bQDyNxWCIXh68J-O9_m7ihR8ym7QYD93dqN0Qs4WheFF5hNPlHDfz1dS_XiAWfNijS-ZqqbW2xVTYvdmqm8RHTeXzXckyu_yMqU-B1')
  st.sidebar.write('Peso muerto 4 series de 12')
  st.sidebar.image('https://www.yomeentreno.com/wp-content/uploads/2018/08/55fe8098-7499-4713-983b-3dd0f0f91baf.gif')
  st.sidebar.write('Zancadas 4 series de 20')
  st.sidebar.image('https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/zancadas-1574679139.gif?resize=320:*')
  st.sidebar.write('Puente 4 series de 15 ')
  st.sidebar.image('https://4.bp.blogspot.com/-NJSk3weT0Ds/WoikpGx2ziI/AAAAAAAAbFE/sAix6msp-QMkeN6BryRDX3aBWnb52TPzwCLcBGAs/s1600/step%2Bby%2Bstep%2Bexercises%2Bpuente.gif')
  st.sidebar.write('Abductor 2 series de 25')
  st.sidebar.image('https://www.dir.cat/blog/wp-content/uploads/2018/10/ejercicios-gluteos-puente.gif')
  st.sidebar.write('Leg Curl 4 series de 12')
  st.sidebar.image('https://thumbs.gfycat.com/AltruisticBothAmericantoad-size_restricted.gif')

if hombre == 'VIERNES':
  st.sidebar.subheader('ESPALDA, BICEPS Y ABDOMEN')
  st.sidebar.write('Comando 4 series de 12')
  st.sidebar.image('https://i.pinimg.com/originals/ee/30/fc/ee30fc219a5cb0cb6d3cbf40cf7272f9.gif')
  st.sidebar.write('Traccion 4 series de 10')
  st.sidebar.image('https://i.pinimg.com/originals/63/bd/12/63bd12e1f39783894f770ad73ae405d5.gif')
  st.sidebar.write('Remo 2 series de 15')
  st.sidebar.image('https://i.pinimg.com/originals/01/03/7f/01037f1ec873a7d00afad45f33f9d865.gif')
  st.sidebar.write('Lagartijas 4 series de 15')
  st.sidebar.image('https://2.bp.blogspot.com/-89XQn-i9jkM/WoslsnsiH_I/AAAAAAAAbIA/AJpIZMuPEFQYr1qhm4k1W74SCvpH4QafgCLcBGAs/s1600/step%2Bby%2Bstep%2Bexercises%2Bflexiones.gif')
  st.sidebar.write('Curl concentrado 2 series de 15')
  st.sidebar.image('https://www.yomeentreno.com/wp-content/uploads/2018/10/6_concentration-Curl.gif')
  st.sidebar.write('Curl con mancuerna 2 series de 15')
  st.sidebar.image('https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/curl-mancuernas-1573207148.gif?resize=320:*')
  st.sidebar.write('Abdominales cortas 4 series de 20')
  st.sidebar.image('https://www.foodspring.de/magazine/wp-content/uploads/2020/11/Crunches-Giannis-1.gif')
  st.sidebar.write('Plancha 4 series de 20 seg')
  st.sidebar.image('https://www.recreoviral.com/wp-content/uploads/2017/01/Plancha.gif')
  st.sidebar.write('Bicicletas 4 series de 20')
  st.sidebar.image('https://2.bp.blogspot.com/-ICToNxoI_Sg/Woh0mJjZ0cI/AAAAAAAAbCw/7_xvGCxu7Mo849NUd3MF3Fy8RJ676BQYwCLcBGAs/s1600/step%2Bby%2Bstep%2Bexercises%2Babdominales%2Bbicicleta.gif')
  st.sidebar.write('Elevacion de piernas 4 series de 20')
  st.sidebar.image('https://www.foodspring.de/magazine/wp-content/uploads/2020/11/Leg-raises-Giannis.gif')

st.subheader('¿Sábes en que más ayuda los alimentos que consumes?')

st.write('**NUTRIGUIA**, te proporciona lo necesario para que puedas descubrir más acerca de que es lo que comes. En la barra lateral, podrás encontrar una variedad de frutas y verduras que puedes elegir para saber un poco sobre ellas.')
st.write('- Selecciona una opción para que se despliegue un dato interesante (dentro de la barra) y algunos beneficios (fuera de la barra) del producto que desees elegir.')
st.image('https://www.salud.mapfre.es/media/2019/10/tipos-de-alimentos-crudos.jpg')

st.sidebar.header('◆ DATOS INTERESANTES Y BENEFICIOS.')

st.sidebar.subheader('FRUTAS.')
fruta= st.sidebar.selectbox('Selecciona la fruta sobre la que quieras saber un poco más.',['','Manzana🍎','Platano🍌','Mango🥭','Sandia🍉','Piña🍍'])
if fruta == 'Manzana🍎':
  st.sidebar.subheader('Dato interesante:')
  st.sidebar.write('Es conocida como la **fruta del pecado** y es una de las más consumidas en todo el mundo. Sirve para hidratar el cuerpo, como diurético, antioxidante y posee una gran cantidad de fibras.')
  st.sidebar.image('https://static4.abc.es/media/bienestar/2019/07/24/manzana-kFeG--620x349@abc.jpg')
  st.subheader('BENEFICIOS DE LA MANZANA.')
  st.write('ES FUENTE DE VITAMINAS Y MINERALES.')
  st.write('- Contribuye al fortalecimiento del sistema inmune y a la disminución de enfermedades del corazón, así como un efecto antidiabético, debido a su capacidad de limitar la absorción de glucosa a nivel intestinal.')
  st.write('- Ayuda a combatir el estreñimiento gracias a la fibra soluble e insoluble. Por lo que es buenísimo comerla con cáscara.')
  st.write('- La piel de la manzana contiene pectina. Este tipo de fibra ayuda a saciar el apetito, por lo que es perfecta para tomarla a media mañana o media tarde para llegar a la comida o a la cena con menos apetito.')
  st.image('https://elespectadordecaracas.com/wp-content/uploads/2021/04/razonescomermanzana-ppal.jpg')
if fruta == 'Platano🍌':
  st.sidebar.subheader('Dato interesante:')
  st.sidebar.write('Los científicos la denominaron **musa sapientum** lo que significa la fruta del hombre sabio.')
  st.sidebar.write('El plátano es bueno para la resaca, por su alto contenido en potasio, nos ayudará a reducir el malestar general provocado por la ingesta excesiva de alcohol.')
  st.sidebar.image('https://dam.cocinafacil.com.mx/wp-content/uploads/2018/11/beneficios-del-platano.jpg')
  st.subheader('BENEFICIOS DEL PLÁTANO.')
  st.write('- Favorece la maduración de otras frutas, a medida que los plátanos maduran segregan gas etileno, el cual acelera el proceso de maduración del resto de frutas y verduras a su alrededor.')
  st.write('- Reduce el riesgo de sufrir una enfermedad cardiovascular, ayuda a reducir la presión arterial y reduce, el riesgo de sufrir una enfermedad de tipo cardiovascular; esto se debe a su alto contenido de potasio.')
  st.write('- Es una fruta perfecta para los deportistas y amantes del running ya que es una fuente de energía indiscutible, ayuda a reforzar nuestro sistema inmunológico.')
  st.image('https://static3.abc.es/media/bienestar/2019/07/25/platano-beneficios-kIyF--1200x630@abc.jpg')
if fruta == 'Mango🥭':
  st.sidebar.subheader('Dato interesante:')
  st.sidebar.write('- El mango más grande del mundo: ¡cerca de 50 cm de diámetro!')
  st.sidebar.write('- Sus familiares cercanos son **frutos secos**.')
  st.sidebar.write('Aunque resulte difícil de creer, los parientes más cercanos del mango son los pistachos, dátiles, la nuez de India, las cerezas y las aceitunas.')
  st.sidebar.image('https://static1.abc.es/media/bienestar/2020/10/13/mango-kueB--620x349@abc.jpg')
  st.subheader('BENEFICIOS DEL MANGO')
  st.write('- Los mangos contienen enzimas digestivas que ayudan a descomponer las proteínas, ayudando a la digestión. También es útil contra la acidez debido a una enzima presente en ella, que alivia el estómago.')
  st.write('- Es útil para los niños que tienen falta de concentración en los estudios, ya que contiene ácido glutamina, que es bueno para estimular la memoria y mantener las células activas. Este acido ayuda en la desintoxicación del cerebro, así como se encarga de evitar el deterioro en la función cerebral.')
  st.write('- Son buenos para las mujeres embarazadas y personas con anemia, debido a su contenido de hierro. La vitamina C en el mango ayuda al cuerpo a absorber el hierro.')
  st.image('https://elproductor.com/wp-content/uploads/2019/11/mangos.jpg')
if fruta == 'Sandía🍉':
  st.sidebar.subheader('Dato interesante:')
  st.sidebar.write('- Hay una variedad de sandía de color amarillo')
  st.sidebar.write('Es difícil de creer que haya una sandía que no sea de color rosa en el interior, pero hay otra variedad, conocida como sandía amarilla, que tiene un interior luminoso y la pulpa tiene un sabor similar a la miel más dulce.')
  st.sidebar.image('https://hablemosdealimentos.com/wp-content/uploads/2018/08/sandia-2.jpg')
  st.subheader('BENEFICIOS DE LA SANDÍA')
  st.write('- Hidrata: La sandía se asocia al verano y no es de extrañar, puesto que es un alimento con gran contenido en agua, el 92% de su composición, y contiene importantes electrolitos.')
  st.write('- Mejora el sistema inmunológico y previene de daños celulares: Fruta rica en vitamina C, que es esencial para nuestro sistema inmunológico, protege nuestro cuerpo y nos ayuda a combatir los resfriados.')
  st.write('- Mejora la salud cardiovascular: Consumir sandía en grandes cantidades, orrelaciona positivamente con la mejora de la función cardiovascular, se incrementa el flujo sanguíneo a través de la vasodilatación.')
  st.image('https://mk0lanoticiapwmx1x6a.kinstacdn.com/wp-content/uploads/2020/08/5-razones-para-comer-sandia-todos-los-dias.jpg')
if fruta == 'Piña🍍':
  st.sidebar.subheader('Dato interesante:')
  st.sidebar.write('Cuando comes piña, ella te come a ti; No te asustes, esto se debe a la sensacion extraña que se da al consumir esta fruta y es provocada ya que la bromelina come proteina, estas enzimas cmeran la superficie de las mejillas, labios y lengua, pero, tranquilo tu lengua reconstruye esas proteinas y aminoacidos rápidamente.')
  st.sidebar.image('https://www.imer.mx/tropicalisima/wp-content/uploads/sites/19/Pin%CC%83a.jpg')
  st.subheader('BENEFICIOS DE LA PIÑA')
  st.write('- DEPURATIVA: La piña es un excelente remedio para el hígado y se sabe que su consumo regular aumenta la circulación en este órgano vital.')
  st.write('- BUENA PARA LA PIEL: Otro de los beneficios de la piña para la salud es que ayuda a limpiar y sanar las úlceras de la piel, y a mejorar la cicatrización de las quemaduras.')
  st.write('- PROTECTORA FRENTE AL CÁNCER: Interfiere en el desarrollo de células ma­lignas (reduciendo el riesgo de metástasis de algunos tipos de cáncer) y parece potenciar los efectos de la quimioterapia.')
  st.image('https://ep01.epimg.net/elpais/imagenes/2019/12/11/buenavida/1576083409_598704_1576083726_noticia_normal.jpg')

st.sidebar.subheader('VERDURAS.')
verdura= st.sidebar.selectbox('Selecciona la verdura sobre la que quieras saber un poco más.',['','Patata🥔','Espinaca🥬','Champiñon/setas🍄','Zanahoria🥕','Aguacate🥑'])
if verdura == 'Patata🥔':
  st.sidebar.subheader('Dato interesante:')
  st.sidebar.write('- Es combustible para vehículos.')
  st.sidebar.write('El almidón de la patata se puede licuar y obtener etanol, base para la producción de combustible. ¡Una moto a patatas!')
  st.sidebar.image('https://i.blogs.es/a696c0/istock-170187164/450_1000.jpg')
  st.subheader('BENEFICIOS DE LA PATATA')
  st.write('- La patata es rica en fibra y muy recomendable para los problemas estomacales ya que combate la acidez. Además, tiene un alto contenido en vitaminas y minerales muy beneficiosos para la piel.')
  st.write('- La patata es un gran alimento a la hora de combatir enfermedades cardiovasculares y reducir la presión arterial.')
  st.write('- Es un alimento rico en carbohidratos, por lo que nos aporta mucha energía. Además, un 75% de su contenido es agua y es una gran fuente de potasio.')
  st.image('https://www.65ymas.com/uploads/s1/21/14/17/patatas-para-freir-asar-o-cocer-cual-escoger-que-las-diferencia.jpeg')
if verdura == 'Espinaca🥬':
  st.sidebar.subheader('Dato interesante:')
  st.sidebar.write('La espinaca tiene importantes compuestos antioxidantes, vitaminas, minerales y elementos saludables para la piel, comerla también contribuye a retardar la aparición de signos prematuros de la edad.')
  st.sidebar.image('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdOqNgFVgoGnkGhY3JOSyA1GL74AjWko05JLo_mHshKiaJtTkNuIXrxupylkjeEZefrOw&usqp=CAU')
  st.subheader('BENEFICIOS DE LA ESPINACA')
  st.write('- **Para los ojos:** Son especialmente importantes para la salud visual. Ayudan a evitar degeneración macular asociada a la edad y cataratas.')
  st.write('- **Vitaminas:** La espinaca es una fuente excelente de vitaminas K, A, C y ácido fólico, rica en manganeso, magnesio, hierro y vitamina B2 (la vitamina K es importante para la salud de los huesos y es difícil encontrar vegetales con más vitamina K que la espinaca).')
  st.write('- **Antiinflamatoria y anticancerígena:** El color verde oscuro de la espinaca indica que contiene altos niveles de carotenoides (betacarotenos, luteína y zeaxantina (los fitoquímicos tienen propiedades antiinflamatorias y anticancerosas).')
  st.image('https://i.blogs.es/5ee30a/istock-522189977/1366_2000.jpg')
if verdura == 'Champiñon/setas🍄':
  st.sidebar.subheader('Dato interesante:')
  st.sidebar.write('Además de tener muchos nutrientes, los hongos son bajos en calorías. Entre el 80 y el 90% de su composición es agua, por lo que su aporte calórico es mínimo.')
  st.sidebar.image('https://lagarnachairapuato.com/wp-content/uploads/2020/07/Hongos-comestibles.jpg')
  st.subheader('BENEFICIOS DE LOS CHAMPIÑONES')
  st.write('- Fortalecen el **sistema inmunitario**, gracias a su contenido en Selenio, este hongo estimula la formación de las células T asesinas, que combaten las células cancerosas e impiden que se creen tumores.')
  st.write('- **Fortalecen el corazón**, al ser ricos en potasio y sodio, estos minerales ayudan a que los niveles de presión arterial no sean elevados, previniendo enfermedades cardiovasculares.')
  st.write('- **Mejoran la diabetes**, los champiñones contienen altas dosis de fibra, y los estudios aseguran que los diabéticos que siguen dietas muy fibrosas, mejoran notablemente sus niveles de azúcar e insulina en sangre.')
  st.image('https://es.intelligentlabs.org/wp-content/uploads/sites/6/2020/01/sopa-de-champinones-keto-05-1024x683.jpg')
if verdura == 'Zanahoria🥕':
  st.sidebar.subheader('Dato interesante:')
  st.sidebar.write('La zanahoria pertenece a la misma familia del apio y el perejil y existen varios tipos de zanahorias y no todas son anaranjadas: ¡hay amarillas rojas y moradas!')
  st.sidebar.image('https://http2.mlstatic.com/D_NQ_NP_975621-MLM29102357685_012019-O.jpg')
  st.subheader('BENEFICIOS DE LAS ZANAHORIAS')
  st.write('- **Vigoriza la mente:** Gracias a su alto contenido en potasio y fósforo, la zanahoria funciona como regeneradora de los nervios, lo que la convierte en un alimento perfecto para vigorizar las mentes cansadas.')
  st.write('- **Previene el envejecimiento:** La zanahoria contiene una gran cantidad de antioxidantes, lo que ayuda a prevenir la aparición de los signos del envejecimiento y ayudan a mantener las piel firme y sin arrugas.')
  st.write('- **Alivia las afecciones respiratorias:** Combinado con jugo de limón o miel, se lograrán aliviar las afecciones respiratorias leves sin tener que tomar ningún medicamento.')
  st.image('https://www.pedidos593.com/canasta-organica/wp-content/uploads/sites/8/2020/04/zanahoria-comun.jpg')
if verdura == 'Aguacate🥑':
  st.sidebar.subheader('Dato interesante:')
  st.sidebar.write('El aguacate no sólo sirve para comer, las mujeres lo utilizan para hacer mascarillas faciales que les ayudan a mantener la piel lozana, incluso sirve para tratamientos de cabello.')
  st.sidebar.image('https://okdiario.com/img/2018/03/12/como-hacer-una-mascarilla-de-aguacate.jpg')
  st.subheader('BENEFICIOS DEL AGUACATE')
  st.write('Los aguacates controlan la tensión arterial, mantienen a raya el colesterol y tienen propiedades antiinflamatorias.')
  st.write('El aguacate contiene magnesio y potasio, minerales que favorecen el buen funcionamiento del sistema nervioso y muscular y son de gran importancia para el sistema inmunológico, y para la salud del intestino delgado y para evitar la retención de líquidos.')
  st.write('Al ser rico en fibra, el aguacate ayuda al organismo a saciar el apetito, evitar el estreñimiento y regular los niveles de glucosa en la sangre.')
  st.image('https://www.tododisca.com/wp-content/uploads/2020/10/aguacate.jpg')
